#!/usr/bin/env python3
"""Clean up songs produced with AI generators (Suno, ElevenLabs, Udio, etc).

Two independent cleanup passes, both opt-in via flags:

  audio    trim a fixed amount off the start/end (where these tools often
           put a spoken/sung tag or an intro stinger), or auto-trim
           leading/trailing silence, with a short fade to avoid clicks;
           optional peak normalization.

  metadata scrub tag fields that name the generator ("Suno", "ElevenLabs",
           "AI generated", ...) or that are pure encoder/tool fingerprints
           (comment, encoder, software), then optionally set your own
           title/artist/album/etc.

Scope note: this only removes what's audible or in plain-text tags. It does
not attempt to detect or defeat inaudible/statistical watermarking embedded
in the waveform itself (e.g. provenance schemes like AudioSeal/SynthID) --
those aren't reliably removable by editing, and this tool doesn't try.

Requires: ffmpeg on PATH, and the `pydub` + `mutagen` Python packages.

Examples:
  # Cut 3s off the start (spoken tag) and 2s off the end, normalize, and
  # clear any AI-generator fingerprints from the tags. Writes alongside
  # the originals under a "cleaned/" folder.
  python3 clean_ai_song.py song.mp3 --trim-start 3 --trim-end 2 --normalize

  # Auto-trim silence, batch over a whole folder, set your own artist tag.
  python3 clean_ai_song.py ./raw_songs --auto-silence-trim \
      --set artist="R.S. Frazier" --set album="Demos"

  # Preview what would happen without writing anything.
  python3 clean_ai_song.py song.wav --auto-silence-trim --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

try:
    from pydub import AudioSegment, effects, silence
except ImportError:
    AudioSegment = None  # type: ignore

try:
    import mutagen
except ImportError:
    mutagen = None  # type: ignore

AUDIO_EXTENSIONS = {".mp3", ".wav", ".flac", ".m4a", ".mp4", ".ogg", ".aac", ".wma"}

DEFAULT_AI_MARKERS = [
    "suno",
    "elevenlabs",
    "eleven labs",
    "udio",
    "mubert",
    "aiva",
    "boomy",
    "soundraw",
    "loudly",
    "beatoven",
    "ai generated",
    "ai-generated",
    "generated by",
    "generated with",
    "created with",
    "made with ai",
]

TECHNICAL_KEY_HINTS = ["comm", "cmt", "encod", "tsse", "tenc", "\xa9too", "software", "tool"]


def stringify(value) -> str:
    if isinstance(value, (list, tuple)):
        return " ".join(stringify(v) for v in value)
    if hasattr(value, "text"):
        return stringify(value.text)
    try:
        return str(value)
    except Exception:
        return ""


def scrub_metadata(path: Path, markers, strip_all: bool, keep_technical: bool, dry_run: bool) -> list[str]:
    """Remove tag fields matching AI markers (or all tags). Returns removed key names."""
    removed: list[str] = []
    f = mutagen.File(path)
    if f is None or f.tags is None:
        return removed

    tags = f.tags
    for key in list(tags.keys()):
        try:
            value = tags[key]
        except Exception:
            continue
        text = stringify(value).lower()
        key_lower = str(key).lower()

        is_ai_marker = any(marker in text for marker in markers)
        is_technical = (not keep_technical) and any(hint in key_lower for hint in TECHNICAL_KEY_HINTS)

        if strip_all or is_ai_marker or is_technical:
            removed.append(str(key))
            if not dry_run:
                del tags[key]

    if removed and not dry_run:
        f.save()
    return removed


def apply_tag_overrides(path: Path, overrides: dict[str, str], dry_run: bool) -> None:
    if not overrides:
        return
    if dry_run:
        return
    f = mutagen.File(path, easy=True)
    if f is None:
        return
    for key, value in overrides.items():
        try:
            f[key] = [value]
        except Exception as exc:
            print(f"  ! could not set tag {key!r}: {exc}", file=sys.stderr)
    f.save()


def process_audio(path: Path, out_path: Path, args) -> str | None:
    """Trim / normalize the audio if any change was requested.

    Returns a summary string and writes out_path, or None (writes nothing)
    if no audio change was requested -- callers should copy the file as-is
    in that case rather than round-tripping it through re-encoding.
    """
    audio = AudioSegment.from_file(path)
    original_len_ms = len(audio)
    summary_parts = []
    trimmed = False

    if args.auto_silence_trim:
        start_silence = silence.detect_leading_silence(audio, silence_threshold=args.silence_thresh_db)
        reversed_audio = audio.reverse()
        end_silence = silence.detect_leading_silence(reversed_audio, silence_threshold=args.silence_thresh_db)
        audio = audio[start_silence: len(audio) - end_silence]
        if start_silence or end_silence:
            trimmed = True
            summary_parts.append(f"auto-trimmed {start_silence}ms silence from start, {end_silence}ms from end")

    start_ms = int(args.trim_start * 1000)
    end_ms = int(args.trim_end * 1000)
    if start_ms or end_ms:
        audio = audio[start_ms: len(audio) - end_ms if end_ms else len(audio)]
        trimmed = True
        summary_parts.append(f"cut {args.trim_start}s from start, {args.trim_end}s from end")

    if not trimmed and not args.normalize:
        return None

    if trimmed and args.fade_ms > 0:
        audio = audio.fade_in(args.fade_ms).fade_out(args.fade_ms)
        summary_parts.append(f"{args.fade_ms}ms fade in/out")

    if args.normalize:
        audio = effects.normalize(audio, headroom=args.normalize_headroom)
        summary_parts.append(f"peak-normalized (headroom {args.normalize_headroom}dB)")

    if not args.dry_run:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_format = args.format or out_path.suffix.lstrip(".") or "mp3"
        # Strip all container metadata on export; sanitized tags get written
        # back separately via mutagen so nothing leaks through re-encoding.
        audio.export(out_path, format=out_format, parameters=["-map_metadata", "-1"])

    new_len_s = len(audio) / 1000.0
    summary_parts.append(f"{original_len_ms / 1000:.1f}s -> {new_len_s:.1f}s")
    return "; ".join(summary_parts)


def copy_unchanged(src: Path, dst: Path, in_place: bool, dry_run: bool) -> Path:
    """No audio processing requested/needed: copy src to dst untouched."""
    if in_place:
        return src
    if not dry_run:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    return dst if not dry_run else src


def discover_inputs(paths: list[str]) -> list[Path]:
    files: list[Path] = []
    for raw in paths:
        p = Path(raw)
        if p.is_dir():
            files.extend(sorted(q for q in p.rglob("*") if q.suffix.lower() in AUDIO_EXTENSIONS))
        elif p.is_file():
            files.append(p)
        else:
            print(f"! skipping {p}: not found", file=sys.stderr)
    return files


def parse_set_args(pairs: list[str]) -> dict[str, str]:
    overrides = {}
    for pair in pairs:
        if "=" not in pair:
            print(f"! ignoring --set {pair!r}: expected KEY=VALUE", file=sys.stderr)
            continue
        key, value = pair.split("=", 1)
        overrides[key.strip().lower()] = value
    return overrides


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("inputs", nargs="+", help="audio file(s) or director(y/ies) to process")
    parser.add_argument("-o", "--output-dir", help="write cleaned files here (default: <input dir>/cleaned/)")
    parser.add_argument("--in-place", action="store_true", help="overwrite the original files instead")
    parser.add_argument("--format", help="override output container/extension (default: keep source)")

    audio_group = parser.add_argument_group("audio cleanup")
    audio_group.add_argument("--trim-start", type=float, default=0.0, metavar="SEC")
    audio_group.add_argument("--trim-end", type=float, default=0.0, metavar="SEC")
    audio_group.add_argument("--auto-silence-trim", action="store_true", help="strip leading/trailing silence")
    audio_group.add_argument("--silence-thresh-db", type=float, default=-40.0)
    audio_group.add_argument("--fade-ms", type=int, default=20, help="fade applied after any trim, 0 to disable")
    audio_group.add_argument("--normalize", action="store_true", help="peak-normalize the output")
    audio_group.add_argument("--normalize-headroom", type=float, default=1.0, metavar="DB")

    meta_group = parser.add_argument_group("metadata cleanup")
    meta_group.add_argument("--strip-all-tags", action="store_true", help="wipe every tag instead of scrubbing")
    meta_group.add_argument("--keep-technical-tags", action="store_true", help="don't remove comment/encoder/software fields")
    meta_group.add_argument("--extra-marker", action="append", default=[], metavar="TEXT", help="extra keyword to scrub (repeatable)")
    meta_group.add_argument("--set", action="append", default=[], dest="set_tags", metavar="KEY=VALUE", help="set a tag after scrubbing (repeatable); works for mp3/flac/m4a/ogg, not wav")
    meta_group.add_argument("--skip-metadata", action="store_true", help="don't touch tags at all")
    meta_group.add_argument("--skip-audio", action="store_true", help="don't touch the waveform at all")

    parser.add_argument("--dry-run", action="store_true", help="report what would happen, write nothing")
    args = parser.parse_args()

    if AudioSegment is None or mutagen is None:
        print("Missing dependencies. Install with: pip install pydub mutagen", file=sys.stderr)
        return 1
    if shutil.which("ffmpeg") is None:
        print("ffmpeg not found on PATH (required by pydub for most formats).", file=sys.stderr)
        return 1

    files = discover_inputs(args.inputs)
    if not files:
        print("No audio files found.", file=sys.stderr)
        return 1

    markers = [m.lower() for m in DEFAULT_AI_MARKERS + args.extra_marker]
    overrides = parse_set_args(args.set_tags)

    for src in files:
        if args.in_place:
            dst = src
        elif args.output_dir:
            dst = Path(args.output_dir) / src.name
        else:
            dst = src.parent / "cleaned" / src.name

        print(f"{src}")

        if args.skip_audio:
            work_path = copy_unchanged(src, dst, args.in_place, args.dry_run)
        else:
            audio_summary = process_audio(src, dst, args)
            if audio_summary is None:
                work_path = copy_unchanged(src, dst, args.in_place, args.dry_run)
                print("  audio: no changes requested (file copied unmodified)")
            else:
                print(f"  audio: {audio_summary}")
                work_path = dst if not args.dry_run else src

        if not args.skip_metadata:
            removed = scrub_metadata(work_path, markers, args.strip_all_tags, args.keep_technical_tags, args.dry_run)
            if removed:
                print(f"  metadata: removed {', '.join(removed)}")
            else:
                print("  metadata: nothing matched")
            apply_tag_overrides(work_path, overrides, args.dry_run)

        if args.dry_run:
            print("  (dry run, nothing written)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
